### ISSUE TITLE
Home link rossz helyre mutat

### ISSUE THREAD

**Issue by miskolci** [morejanos/raktar#1]
A fejlécben lévő "home link" a www.example.com-ra mutat jelenleg. Így ha valaki rákattint a fejlécben lévő "Raktár nyilvántartó" feliratra, akkor el akar navigálni erre a rossz linkre.

![raktar_nyilvantarto_issue1](https://cloud.githubusercontent.com/assets/18248512/15689084/9c83aa44-277d-11e6-870f-4bf8169ed9c0.jpg)

**Comment by morejanos** [comment]
Értem főnök. Már ki lett javítva :)
