### ISSUE TITLE
A készletnél több alkatrész kivételénél zöld hibaüzenet jön

### ISSUE THREAD

**Issue by miskolci** [morejanos/raktar#4]
" Error: Nem lehet kivenni több alkatrészt, mint amennyi a raktárban van" üzenet piros legyen!

![zold_error](https://cloud.githubusercontent.com/assets/18248512/16871248/2b9af00e-4a86-11e6-9b36-7bae7179f068.png)

**Comment by morejanos** [comment]
Notice megváltoztatva warning-ra.
