### ISSUE TITLE
Alkatrész rendelés funkció bővítési igény

### ISSUE THREAD

**Issue by miskolci** [morejanos/raktar#7]
Felmerült egy lehetséges igény a raktárkezelő programhoz.
Jelenleg egy sima megosztott táblázatba írják a fiúk azokat az alkatrészeket, amiket szeretnének, ha megrendelnénk, mert mondjuk egy új alkatrészről van szó, ami még nincs a jelenlegi rendszerben (mert még soha nem használtunk olyat). Ez eddig úgy működött, hogy a fiúk folyamatosan töltötték ezt a táblázatot és Robi időnként, mondjuk hetente ránézett és megrendelte őket. 

Arra gondoltam, hogy bővíteni lehetne egy új menüponttal a raktárkezelőt. Pl. Alkatrész igénylés. Ha erre kattintanak, akkor pár mezőben felvihetnének a fiúk rendelendő alkatrészről adatokat (Alkatresz megnevezése  Darabszám  Cikkszam    Tokozás    Mihez?  Igény dátum   Rendelési dátum   Honnan?)
Tehát ezeket az adatokat manuálisan vinné fel mindenki. Viszont van az automata figyelmeztető rendszer ami már most is működik, mikor a kritikus darabszám alá esik egy alkatrész darabszáma. Na, ez jó lenne, ha ezentúl nem csak e-mailt küldene, hanem erre az új alkatrész igénylő listába is automatán bekerülne a manuálisok közé. Nyilván a már korábban létező alkatrészekről nem kell beírni a fent zárójelben megadott adatokat, csak legyenek benne az igénylés listában.

Na, hirtelen ennyi. Majd személyesen a részleteket megbeszéljük.

**Comment by morejanos** [comment]
Barmelyik user fel tudjon venni új alkatrészt.
Ez Új Alktrész Igény" rendelési státuszú lesz.
Kötelező attributomokat SW-ből adom hozzá, előre lefolalt Location-re.
