### ISSUE TITLE
"Megrendelve" + megrendelés dátuma mezők

### ISSUE THREAD

**Issue by miskolci** [morejanos/raktar#8]
Szeretnénk egy újabb funkciót/információt feltüntetni az alkatrészeknél. Ha valamelyik alkatrészből lett rendelve már, mert mondjuk fogyóban volt, akkor tüntesse fel a program információként, hogy az adott anyag már meg lett rendelve, illetve, hogy mikor.
Azért lenne ez jó, mert mondjuk én már megrendeltem egy anyagot, de minden egyes kivétnél újra és újra küldi a figyelmeztetést a rendszer, nehogy mondjuk Robi is berendelje ugyanazt, ha én nem vagyok mondjuk bent.

**Comment by morejanos** [comment]
Új tábla hozzáadása.
Rendelési status.
  Állapotok:  
- Rendelési igény
- Megrendelve
- Nincs Rendelési igény

Compnents táblába új link hozzáadása a Rendelési Státuszra.
